<a href="https://colab.research.google.com/github/highRisk911/Lab1/blob/main/LR2.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Лабораторна робота 2
Іщенка Дмитра Романовича


In [ ]:
import tensorflow as tf
# print(tf.__version__)
import numpy as np
import pandas as pd

# Tensor creation

In [ ]:
 
scalar = tf.constant(999)
print(scalar)
print(scalar.ndim)
 
vector = tf.constant([9, 9, 9])
print(vector)
print(vector.ndim)
 
matrix = tf.constant([[1, 1], [2, 2]])
print(matrix)
print(matrix.ndim)
 
 
matrix_tensor = tf.Variable([[1, 1], [2, 2]])
print(matrix_tensor)
 
matrix_tensor[0].assign([9, 9])
print(matrix_tensor)

 

random_1 = tf.random.Generator.from_seed(42)
print(random_1.normal(shape=(2, 3)))
 

unshuffled = tf.constant([1, 2, 3])
shuffled = tf.random.shuffle(unshuffled)
print(shuffled)
 

ones = tf.ones(shape=(1, 5))
zeros = tf.zeros(shape=(2, 2))
print(ones)
print(zeros)
 

numpy_array = np.arange(1, 10)
tensor_from_np_array = tf.constant(numpy_array, shape=(3, 3))
print(tensor_from_np_array)

tf.Tensor(999, shape=(), dtype=int32)
0
tf.Tensor([9 9 9], shape=(3,), dtype=int32)
1
tf.Tensor(
[[1 1]
 [2 2]], shape=(2, 2), dtype=int32)
2
<tf.Variable 'Variable:0' shape=(2, 2) dtype=int32, numpy=
array([[1, 1],
       [2, 2]], dtype=int32)>
<tf.Variable 'Variable:0' shape=(2, 2) dtype=int32, numpy=
array([[9, 9],
       [2, 2]], dtype=int32)>
tf.Tensor(
[[-0.7565803  -0.06854702  0.07595026]
 [-1.2573844  -0.23193765 -1.8107855 ]], shape=(2, 3), dtype=float32)
tf.Tensor([2 1 3], shape=(3,), dtype=int32)
tf.Tensor([[1. 1. 1. 1. 1.]], shape=(1, 5), dtype=float32)
tf.Tensor(
[[0. 0.]
 [0. 0.]], shape=(2, 2), dtype=float32)
tf.Tensor(
[[1 2 3]
 [4 5 6]
 [7 8 9]], shape=(3, 3), dtype=int64)


# Getting info from tensors

In [ ]:
custom_tensor = tf.ones(shape=(3, 4, 4))

print(custom_tensor)
 

print(custom_tensor.shape)
print(custom_tensor.ndim)
print(tf.size(custom_tensor))
print(tf.rank(custom_tensor))

tf.expand_dims(custom_tensor, axis=-1)

tf.Tensor(
[[[1. 1. 1. 1.]
  [1. 1. 1. 1.]
  [1. 1. 1. 1.]
  [1. 1. 1. 1.]]

 [[1. 1. 1. 1.]
  [1. 1. 1. 1.]
  [1. 1. 1. 1.]
  [1. 1. 1. 1.]]

 [[1. 1. 1. 1.]
  [1. 1. 1. 1.]
  [1. 1. 1. 1.]
  [1. 1. 1. 1.]]], shape=(3, 4, 4), dtype=float32)
(3, 4, 4)
3
tf.Tensor(48, shape=(), dtype=int32)
tf.Tensor(3, shape=(), dtype=int32)


<tf.Tensor: shape=(3, 4, 4, 1), dtype=float32, numpy=
array([[[[1.],
         [1.],
         [1.],
         [1.]],

        [[1.],
         [1.],
         [1.],
         [1.]],

        [[1.],
         [1.],
         [1.],
         [1.]],

        [[1.],
         [1.],
         [1.],
         [1.]]],


       [[[1.],
         [1.],
         [1.],
         [1.]],

        [[1.],
         [1.],
         [1.],
         [1.]],

        [[1.],
         [1.],
         [1.],
         [1.]],

        [[1.],
         [1.],
         [1.],
         [1.]]],


       [[[1.],
         [1.],
         [1.],
         [1.]],

        [[1.],
         [1.],
         [1.],
         [1.]],

        [[1.],
         [1.],
         [1.],
         [1.]],

        [[1.],
         [1.],
         [1.],
         [1.]]]], dtype=float32)>

# Math oprations with tensors

In [ ]:
tensor = tf.constant([[1, 2, 3],
                      [1, 2, 3]])
 
print(tensor + 5)
print(tensor - 5)
print(tf.multiply(tensor, 5))

  
print(tensor @ tf.reshape(tensor, shape=(3, 2))) # 1 way
print(tf.matmul(tensor, tf.transpose(tensor))) # 2 way


negative_tensor = tf.constant([[-1, -2, -3], [-1, -2, -3]])

print(tf.abs(negative_tensor))
print(tf.reduce_max(negative_tensor))
print(tf.reduce_mean(negative_tensor))

tf.Tensor(
[[6 7 8]
 [6 7 8]], shape=(2, 3), dtype=int32)
tf.Tensor(
[[-4 -3 -2]
 [-4 -3 -2]], shape=(2, 3), dtype=int32)
tf.Tensor(
[[ 5 10 15]
 [ 5 10 15]], shape=(2, 3), dtype=int32)
tf.Tensor(
[[13 13]
 [13 13]], shape=(2, 2), dtype=int32)
tf.Tensor(
[[14 14]
 [14 14]], shape=(2, 2), dtype=int32)
tf.Tensor(
[[1 2 3]
 [1 2 3]], shape=(2, 3), dtype=int32)
tf.Tensor(-1, shape=(), dtype=int32)
tf.Tensor(-2, shape=(), dtype=int32)


# CRUD, reshape, np.array, pd.DataFrame

In [ ]:
tensor = tf.Variable([[1, 1], [2, 2], [3, 3]])

tf.compat.v1.assign(tensor[0], [999, 999])
print(tensor)

tensor = tf.sqrt(tf.cast(tensor, dtype=tf.float32))
print(tensor)

tensor = tf.square(tensor)
print(tensor)

one_dimension_tensor = tf.random.Generator.from_seed(10)
one_dimension_tensor = tf.reshape(one_dimension_tensor.normal(shape=(3, 2)), shape=(2, 3))
print(one_dimension_tensor)


# numpy
N = tf.Variable(np.array([1, 2, 3, 4]))
print(N.numpy())
print(N)


# pandas
P = tf.Variable(pd.DataFrame([1, 2, 3, 4]))
print(P)

<tf.Variable 'Variable:0' shape=(3, 2) dtype=int32, numpy=
array([[999, 999],
       [  2,   2],
       [  3,   3]], dtype=int32)>
tf.Tensor(
[[31.60696   31.60696  ]
 [ 1.4142135  1.4142135]
 [ 1.7320508  1.7320508]], shape=(3, 2), dtype=float32)
tf.Tensor(
[[998.99994   998.99994  ]
 [  1.9999999   1.9999999]
 [  3.          3.       ]], shape=(3, 2), dtype=float32)
tf.Tensor(
[[-0.29604465 -0.21134207  0.01063002]
 [ 1.5165398   0.2730574  -0.29925638]], shape=(2, 3), dtype=float32)
[1 2 3 4]
<tf.Variable 'Variable:0' shape=(4,) dtype=int64, numpy=array([1, 2, 3, 4])>
<tf.Variable 'Variable:0' shape=(4, 1) dtype=int64, numpy=
array([[1],
       [2],
       [3],
       [4]])>


# Висновок
На даній лабораторній роботі було використино багато базовий функціонал бібліотеки TensorFlow, що допомагає ефективно обробляти дані та представляє дуже прости api для роботи з великими масивами даних. Також було застосовано TF для опрацювання numpy масивів та pandas дата фреймів.